### ISSUE TITLE
TypeError on admin changelist

### ISSUE THREAD

**Issue by czpython** [ionelmc/django-redisboard#13]
Hello,

When visiting the changelist page of redisboard in admin I get

```TypeError: a float is required```

the error happens exactly on line 165 in [here](https://github.com/ionelmc/django-redisboard/blob/master/src/redisboard/models.py#L165).

The reason for the error is because at this point the values of ```ts```, ```id```, ```command```, etc.. are the keys of the dictionary in https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L272 instead of the actual values because of the ```enumerate``` call.

**Comment by ionelmc** [comment]
So it's in the master, there's going to be a new release soonish.

**Comment by ionelmc** [comment]
Released now: https://pypi.python.org/pypi/django-redisboard/1.1.0
