### ISSUE TITLE
Exception in AWS ElastiCache Redis

### ISSUE THREAD

**Issue by jolks** [ionelmc/django-redisboard#20]
AWS ElastiCache Redis does not have DEBUG OBJECT command.
![AWS ElastiCache Redis does not have DEBUG OBJECT command](https://cloud.githubusercontent.com/assets/765292/10397095/e9b3a824-6ee0-11e5-9c0c-9561f1369c7e.png)

Just having try/catch is unfortunately not enough to bypass the exception and still be able to inspect the key.
![screen shot 2015-10-09 at 11 23 42 pm](https://cloud.githubusercontent.com/assets/765292/10397194/5a0578be-6ee1-11e5-9bed-adbe7cf3c14c.png)

**Comment by ionelmc** [comment]
This would be fixed by #19 right?

**Comment by jolks** [comment]
Yes, thanks for linking both up.
