### ISSUE TITLE
Key data represented as bytes

### ISSUE THREAD

**Issue by eriktelepovsky** [ionelmc/django-redisboard#30]
Hi.

I am saving datetime object into cache. Example:

```
cache.set(cache_key, now(), 60, version=1)
```

In the Django admin, while inspecting the key, bytes are shown up, like this:

```
(b'\x80\x04\x95=\x00\x00\x00\x00\x00\x00\x00\x8c\x08datetime\x94\x8c\x08date' b'time\x94\x93\x94C\n\x07\xe1\x04\x0f\r1\x15\x08\x7f\xa8\x94\x8c\x04py' b'tz\x94\x8c\x04_UTC\x94\x93\x94)R\x94\x86\x94R\x94.')
```

I would rather expect showing the corresponding text representation of the object:

```
datetime.datetime(2017, 4, 15, 13, 35, 51, 169443, tzinfo=<UTC>)
```

Is it possible? Or am I doing something wrong?

Environment:

```
$ pip freeze|grep redis
django-redis==4.7.0
django-redisboard==3.0.2
redis==2.10.5

$ pip freeze|grep Django
Django==1.11

$ python --version
Python 3.5.2
```

**Comment by ionelmc** [comment]
Unlikely to see something builtin for this in redisboard. Perhaps something you could extend so you can implement your own custom text representer (if it's a unpickler read it as "foot gun" 😁)?

Do you really need this?

**Comment by mr2rm** [comment]
Hi.
Do you have any plan to resolve this issue?
I can contribute to fixing it if you want.

**Comment by ionelmc** [comment]
Well the plan was to have some sort of api to set your own decoding routines. Something like a function you put in the settings, perhaps along the lines of what debug toolbar has https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#debug-toolbar-config ?

**Comment by ionelmc** [comment]
Eg:

```py
REDISBOARD_DECODERS = {
 '.*': pickle.loads
}
```
or even

```py
REDISBOARD_DECODERS = {
 (lambda s: 'foobar' in s): pickle.loads
}
```

**Comment by mr2rm** [comment]
@ionelmc 
Awesome! We are of one mind. That’s just what I was thinking.
Do you think the decoders should work database-oriented or key-related?

> Eg:
> 
> ```python
> REDISBOARD_DECODERS = {
>  '.*': pickle.loads
> }
> ```
> 
> or even
> 
> ```python
> REDISBOARD_DECODERS = {
>  (lambda s: 'foobar' in s): pickle.loads
> }
> ```

**Comment by ionelmc** [comment]
Maybe change the models to opt in certain decoders for certain servers? Lemme think a bit.

**Comment by mr2rm** [comment]
@ionelmc Any word on your thoughts? Could you decide about the solution?

**Comment by ionelmc** [comment]
Ok so settings-wise i think we could have something like this by default:
```python
import pickle

def repr_pickle(value):
    try:
        return repr(pickle.loads(value))
    except Exception as exc:
        return f'Unpickle failure: {exc}. Value: {value!r}'

REDISBOARD = {
    'decoders': {
        'default': repr,
        'pickle': repr_pickle,
    }
}
```

Regarding the server configuration I am think that a chart field with the decoder name would be adequate. 

Then you can implement custom matching/fallback or whatever you need in your custom unpickle decoder.

**Comment by ionelmc** [comment]
FYI I started adding support for customizing this tho it's way different as I realized the previous internals are a busted [1] and there is need for separate paths for each redis type (in addition to key name). 

[1]. (the pagination was really broken and lots of other issues)

I have a work in progress in here https://github.com/ionelmc/django-redisboard/tree/wip - you can take a look at what is most likely to end up in master :-) Take a look at those decoder classes to get a feeling of the changes.

In theory it would be possible to add fields on the model to customize what class is active, but not yet implemented - @mr2rm if you'd still like to contribute. We could also have some classes to support libraries (eg: celery stuff). Throw in ideas.

The bare minimum to support pickles is:

```python
class PickleDecoder(BaseDecoder):
    def bytes(self, key: str, value: bytes):
        return pickle.loads(value)
```

This allows doing something depending on key name and and you can implement methods for the various types if you have type-specific deserialization.
